<a href="https://colab.research.google.com/github/arad4228/BigData_and_A.I/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EC%9D%91%EC%9A%A9(4%EC%9B%94%2014%EC%9D%BC%20%EC%8B%A4%EC%8A%B5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.model_selection import  train_test_split

In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
from sklearn.metrics import mean_squared_error

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [5]:
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()

In [6]:
diabetes

{'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, total serum cholesterol\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, total cholesterol / HDL\n      - s5      ltg, possibly log of serum triglycerides level\n      - s6      glu, b

In [7]:
x,y = diabetes["data"], diabetes["target"]

In [8]:
x[0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613])

In [9]:
x[1]

array([-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
       -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405])

In [10]:
x[2]

array([ 0.08529891,  0.05068012,  0.04445121, -0.00567061, -0.04559945,
       -0.03419447, -0.03235593, -0.00259226,  0.00286377, -0.02593034])

In [11]:
x[3]

array([-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
        0.02499059, -0.03603757,  0.03430886,  0.02269202, -0.00936191])

In [13]:
x[4]

array([ 0.00538306, -0.04464164, -0.03638469,  0.02187235,  0.00393485,
        0.01559614,  0.00814208, -0.00259226, -0.03199144, -0.04664087])

In [17]:
y[0]

151.0

In [18]:
train_x, test_x, train_y, test_y = train_test_split(x,y,test_size = 0.2)

In [19]:
len(x), len(train_x), len(test_x), len(train_y), len(test_y)

(442, 353, 89, 353, 89)

In [20]:
regressor = LinearRegression ()
regressor.fit (train_x,train_y)

LinearRegression()

In [21]:
regressor.coef_

array([ -33.89384662, -243.73306291,  526.06786385,  332.39473875,
       -812.36626507,  525.80146097,  105.39954843,   99.9941361 ,
        814.12491948,   64.35489639])

In [24]:
train_pred = regressor.predict(train_x)
test_pred = regressor.predict(test_x)
print(train_pred, test_pred)

[227.08611379  95.74325957 221.69387049  96.51077373 200.33795998
 127.57347334 160.21211033  82.4737282   52.28629413 189.28514108
 134.84581874 221.03233518 174.05701308 155.13754715 175.20970642
 129.75740353 170.34497813 233.86472159  88.71487399 155.47656854
  97.7691108  117.3010515   73.28477661 280.07962902 196.07203852
 142.95103411 134.43157085 189.1668042  149.33502718  78.24353055
 159.00986762  64.56313891 274.55457208 115.5573502  125.06273418
  75.69567946  78.21031294 204.1701652  106.34141037 126.88680539
 108.37455003 111.59740582 270.56071079 100.37279154 252.7667209
 229.18420586 178.18255    104.88433629 116.65995764 254.74129999
 250.23038647  89.2714941  149.90142168 236.44849714 276.66198106
 128.38594368 170.22958551 259.59448202 105.99470256 158.17644473
 148.24615796 112.94916277 162.99377436 101.44380034  64.15831546
 100.82604492 257.46288846  49.90896302 109.24419811 104.52185502
 124.38635249 208.65225701 119.82708542 185.71046113 200.90134844
 239.051154

In [23]:
train_mse = mean_squared_error(train_pred, train_y)
test_mse = mean_squared_error(test_pred, test_y)
print(train_mse,test_mse)

2910.9632190126254 2703.536348473019
