<a href="https://colab.research.google.com/github/arad4228/BigData_and_A.I/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%9D%91%EC%9A%A9_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.model_selection import  train_test_split

In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
from sklearn.metrics import mean_squared_error

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(2001)

In [7]:
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()

In [10]:
diabetes

{'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, total serum cholesterol\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, total cholesterol / HDL\n      - s5      ltg, possibly log of serum triglycerides level\n      - s6      glu, b

In [9]:
x,y = diabetes["data"], diabetes["target"]

In [15]:
x[0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613])

In [16]:
x[1]

array([-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
       -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405])

In [17]:
x[2]

array([ 0.08529891,  0.05068012,  0.04445121, -0.00567061, -0.04559945,
       -0.03419447, -0.03235593, -0.00259226,  0.00286377, -0.02593034])

In [18]:
x[3]

array([-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
        0.02499059, -0.03603757,  0.03430886,  0.02269202, -0.00936191])

In [19]:
x[4]

array([ 0.00538306, -0.04464164, -0.03638469,  0.02187235,  0.00393485,
        0.01559614,  0.00814208, -0.00259226, -0.03199144, -0.04664087])

In [11]:
train_x, test_x, train_y, test_y = train_test_split(x,y,test_size = 0.2)

In [13]:
len(x), len(train_x), len(test_x), len(train_y), len(test_y)

(442, 353, 89, 353, 89)

In [22]:
regressor = LinearRegression ()
regressor.fit (train_x,train_y)

LinearRegression()

In [24]:
regressor.coef_

array([ -10.40163539, -258.67135416,  499.97531965,  344.36757767,
       -781.66269977,  434.40900543,   59.33403486,  122.83322334,
        763.00351366,   95.39404004])

In [30]:
train_pred = regressor.predict(train_x)
test_pred = regressor.predict(test_x)
print(train_pred, test_pred)

[150.27950681 171.60554432 132.21487501 161.19853609 217.29356464
 217.43856976 144.19678807 219.11106193 144.97114408 120.91013334
  95.48057984 261.45544922 129.45749883  73.25032567 167.83324561
 144.58679253  78.56368402  83.74236595 150.85048836 253.81281118
 203.2083153  180.1515816  132.49207395 166.43066215 212.50041031
 126.1188806  250.63854564 102.87767271 218.73096263 166.68516772
  92.63289569  85.01250649 225.42633594 272.32039212 176.07585151
 134.13677445 204.58405317 188.70953892 165.62483765 216.43827066
 262.55688507 206.05039826 204.48306181 136.5773069  229.78212706
 217.82897217  64.3482584  233.12609454 123.62566621  53.586436
 236.2585582  195.79871016 210.15245053  87.53230892 183.28524451
  84.66628743  78.49846245 101.95012986 133.403878    89.46021647
 123.15022379 241.44957553 295.76883039 176.76935198  83.42434536
 151.52077935 123.33116642 118.09093164 150.20203683  39.66089128
  79.87948665 165.74615121 109.95926663 148.06665359 124.00414009
 114.9203216

In [31]:
train_mse = mean_squared_error(train_pred, train_y)
test_mse = mean_squared_error(test_pred, test_y)
print(train_mse,test_mse)

2696.230216966471 3567.4952788466335
